apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-exec
  namespace: emr-data-team-a
spec:
  volumes:
    - name: metrics-files-volume
      emptyDir: {}
    - name: spark-local-dir-ny-taxi
      hostPath:
        path: /local1
        type: DirectoryOrCreate

  nodeSelector:
    "NodeGroupType": "spark"

  containers:
    - name: spark-kubernetes-executor # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-ny-taxi
          mountPath: /local1/ny-taxi
        - name: metrics-files-volume
          mountPath: /var/metrics/data
